Repository Ulm-IQO/qudi, pull requests merged in 2020-04, with the labels that each got.

#570 Qo fastcounter hotfix
  hardware/fpga_fastcounter/fast_counter_fpga_qo.py
Labels: bug, comp:fast_counter, comp:pulsed

#588 Awg 7k constraint fix
  documentation/changelog.md
  hardware/awg/tektronix_awg7k.py
Labels: bug, comp:pulsed

#592 Some improvements to the qudi plotter:
  config/example/default.cfg
  gui/qdplotter/qdplotter_gui.py
  gui/qdplotter/ui_parameter_widget.ui
  gui/qdplotter/ui_plot_widget.ui
  gui/qdplotter/ui_qdplotter.ui
  logic/qdplot_logic.py
Labels: bug, design issue, enhancement

#590 QDPlotter improvements
  config/example/default.cfg
  documentation/changelog.md
  gui/qdplotter/qdplotter_gui.py
  gui/qdplotter/qdplottergui.py
  gui/qdplotter/ui_plot_widget.ui
  gui/qdplotter/ui_qdplotter.ui
  logic/qdplot_logic.py
Labels: design issue, enhancement
